version: '3.8'

services:
  api-manager:
    build: .
    container_name: watchme-api-manager
    ports:
      - "9001:9001"
    environment:
      - NODE_ENV=production
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
      - VITE_PORT=9001
      - VITE_API_TIMEOUT=${VITE_API_TIMEOUT}
    restart: unless-stopped